# Generated by Django 3.0.3 on 2020-03-24 07:34

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0038_memotemplatemaintenance_paymentmodemaintenance_transactiontypemaintenance'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='document_source',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='attachment',
            field=models.FileField(default=1, upload_to='', verbose_name='File Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='attachment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentcreated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentmodified_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.PaymentmodeMaintenance', verbose_name='Payment Mode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='remarks',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='transaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.TransactiontypeMaintenance', verbose_name='Trans. Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentRequestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linenum', models.IntegerField()),
                ('item_description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parent_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentRequest')),
                ('tax', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.TaxMaintenance')),
            ],
            options={
                'verbose_name': 'Payment Detail',
            },
        ),
    ]
