# Generated by Django 3.0.3 on 2020-03-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200324_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='revision',
            field=models.IntegerField(),
        ),
    ]
