# Generated by Django 3.0.3 on 2020-03-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200324_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='document_number',
            field=models.CharField(max_length=100, verbose_name='Document No'),
        ),
    ]
