# Generated by Django 3.0.3 on 2020-03-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200325_0146'),
        ('payment', '0004_auto_20200325_1643'),
    ]

    operations = [
    ]
