# Generated by Django 3.0.3 on 2020-03-26 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_merge_20200326_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='attachment_date',
        ),
        migrations.CreateModel(
            name='PaymentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='', verbose_name='File Name')),
                ('attachment_date', models.DateField(auto_now_add=True)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentRequest', verbose_name='PaymentRequest')),
            ],
            options={
                'verbose_name': 'Attachment',
            },
        ),
    ]
