# Generated by Django 3.0.3 on 2020-03-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200328_2201'),
        ('payment', '0005_merge_20200326_0351'),
    ]

    operations = [
    ]
