# Generated by Django 3.0.3 on 2020-03-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_merge_20200329_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequestdetail',
            old_name='parent_id',
            new_name='pr',
        ),
    ]
