# Generated by Django 3.0.3 on 2020-03-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0053_auto_20200329_1237'),
        ('payment', '0009_auto_20200329_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.CurrencyMaintenance', verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeMaintenance', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.VendorMasterData', verbose_name='Vendor'),
        ),
    ]
