# Generated by Django 3.0.3 on 2020-03-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20200329_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequestdetail',
            name='linenum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
