# Generated by Django 3.0.3 on 2020-03-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20200329_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequestdetail',
            name='linenum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
