# Generated by Django 3.0.3 on 2020-03-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20200329_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequestdetail',
            old_name='pr',
            new_name='py',
        ),
    ]
