# Generated by Django 3.0.3 on 2020-03-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20200329_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequestdetail',
            name='py',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentRequest'),
        ),
    ]
