# Generated by Django 3.0.3 on 2020-03-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20200329_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequestdetail',
            name='linenum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequestdetail',
            name='py',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentRequest'),
        ),
    ]
