# Generated by Django 3.0.3 on 2020-03-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20200329_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentattachment',
            old_name='payment_request',
            new_name='py',
        ),
    ]
