# Generated by Django 3.0.3 on 2020-03-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20200329_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentattachment',
            name='py',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentRequest', verbose_name='PaymentRequest'),
        ),
    ]
