# Generated by Django 3.0.3 on 2020-03-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_auto_20200329_1812'),
        ('payment', '0007_merge_20200328_2221'),
    ]

    operations = [
    ]
