# Generated by Django 3.0.3 on 2020-03-30 02:41

from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_auto_20200330_0359'),
        ('payment', '0019_merge_20200330_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalItem', verbose_name='Approval'),
        ),
        migrations.AlterField(
            model_name='paymentattachment',
            name='attachment',
            field=models.FileField(upload_to=payment.models.documenttype_directory_path, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='document_number',
            field=models.CharField(default=payment.models.documenttype_document_number, max_length=100, verbose_name='Document No'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(blank=True, default='D', max_length=1, null=True),
        ),
    ]
