# Generated by Django 3.0.4 on 2020-04-02 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_auto_20200402_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='submit_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
