# Generated by Django 3.0.4 on 2020-04-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20200402_2318'),
        ('payment', '0027_auto_20200402_1808'),
    ]

    operations = [
    ]
