# Generated by Django 3.0.3 on 2020-04-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_auto_20200403_1619'),
        ('payment', '0029_auto_20200404_1420'),
    ]

    operations = [
    ]
