# Generated by Django 3.0.3 on 2020-04-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_merge_20200404_1548'),
        ('payment', '0027_auto_20200404_1614'),
    ]

    operations = [
    ]
