# Generated by Django 3.0.3 on 2020-04-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_merge_20200404_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
