# Generated by Django 3.0.3 on 2020-04-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_auto_20200406_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequestdetail',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
