# Generated by Django 3.0.3 on 2020-04-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_auto_20200410_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequestdetail',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
