# Generated by Django 3.0.5 on 2020-04-21 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0074_merge_20200421_1216'),
        ('payment', '0034_auto_20200415_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='utility_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.UtiliyAccountTypeMaintenance', verbose_name='Utility Account'),
        ),
    ]
