# Generated by Django 3.0.5 on 2020-04-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility_dashboard', '0001_initial'),
        ('payment', '0035_paymentrequest_utility_account'),        
        ('administration', '0074_merge_20200421_1216'), 
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='utility_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility_dashboard.UtilityApprovalItem', verbose_name='Utility Approval'),
        ),
    ]
