# Generated by Django 3.0.5 on 2020-04-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0077_auto_20200421_1920'),
        ('payment', '0037_auto_20200421_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='document_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.DocumentTypeMaintenance'),
        ),
    ]
