# Generated by Django 3.0.3 on 2020-03-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0014_auto_20200310_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('submit_date', models.DateField()),
                ('subject', models.CharField(max_length=250)),
                ('reference', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CurrencyMaintenance', verbose_name='Currency')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ProjectMaintenance', verbose_name='Project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.VendorMasterData', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
    ]
