# Generated by Django 3.0.4 on 2020-04-04 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0066_workflowapprovalrule_ceo_approve_overwrite'),
        ('fixed_asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaster',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company'),
        ),
    ]
