# Generated by Django 3.0.4 on 2020-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_asset', '0002_assetmain_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmain',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
