# Generated by Django 3.0.4 on 2020-04-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_asset', '0003_auto_20200406_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaster',
            name='asset_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.AssetCategory'),
        ),
        migrations.AlterField(
            model_name='assetmaster',
            name='asset_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.AssetType'),
        ),
        migrations.AlterField(
            model_name='assetmaster',
            name='class_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.ClassType'),
        ),
        migrations.AlterField(
            model_name='assetmaster',
            name='tax_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixed_asset.Tax'),
        ),
    ]
