BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "auth_group" (
	"id"	integer NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	varchar(150) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "auth_permission" (
	"id"	integer NOT NULL PRIMARY KEY AUTOINCREMENT,
	"content_type_id"	integer NOT NULL,
	"codename"	varchar(100) NOT NULL,
	"name"	varchar(255) NOT NULL,
	FOREIGN KEY("content_type_id") REFERENCES "django_content_type"("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" (
	"id"	integer NOT NULL PRIMARY KEY AUTOINCREMENT,
	"user_id"	integer NOT NULL,
	"permission_id"	integer NOT NULL,
	FOREIGN KEY("permission_id") REFERENCES "auth_permission"("id") DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY("user_id") REFERENCES "auth_user"("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS "auth_user_groups" (
	"id"	integer NOT NULL PRIMARY KEY AUTOINCREMENT,
	"user_id"	integer NOT NULL,
	"group_id"	integer NOT NULL,
	FOREIGN KEY("group_id") REFERENCES "auth_group"("id") DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY("user_id") REFERENCES "auth_user"("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" (
	"id"	integer NOT NULL PRIMARY KEY AUTOINCREMENT,
	"group_id"	integer NOT NULL,
	"permission_id"	integer NOT NULL,
	FOREIGN KEY("permission_id") REFERENCES "auth_permission"("id") DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY("group_id") REFERENCES "auth_group"("id") DEFERRABLE INITIALLY DEFERRED
);
INSERT INTO "auth_group" ("id","name") VALUES (1,'Group B');
INSERT INTO "auth_group" ("id","name") VALUES (2,'Group A');
INSERT INTO "auth_group" ("id","name") VALUES (3,'General Officer/Executive');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (1,1,'add_companymaintenance','Can add company maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (2,1,'change_companymaintenance','Can change company maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (3,1,'delete_companymaintenance','Can delete company maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (4,1,'view_companymaintenance','Can view company maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (5,2,'add_departmentmaintenance','Can add department maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (6,2,'change_departmentmaintenance','Can change department maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (7,2,'delete_departmentmaintenance','Can delete department maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (8,2,'view_departmentmaintenance','Can view department maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (9,3,'add_projectmaintenance','Can add project maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (10,3,'change_projectmaintenance','Can change project maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (11,3,'delete_projectmaintenance','Can delete project maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (12,3,'view_projectmaintenance','Can view project maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (13,4,'add_statusmaintenance','Can add status maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (14,4,'change_statusmaintenance','Can change status maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (15,4,'delete_statusmaintenance','Can delete status maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (16,4,'view_statusmaintenance','Can view status maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (17,5,'add_workflowinstance','Can add workflow instance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (18,5,'change_workflowinstance','Can change workflow instance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (19,5,'delete_workflowinstance','Can delete workflow instance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (20,5,'view_workflowinstance','Can view workflow instance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (21,6,'add_workflowpattern','Can add workflow pattern');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (22,6,'change_workflowpattern','Can change workflow pattern');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (23,6,'delete_workflowpattern','Can delete workflow pattern');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (24,6,'view_workflowpattern','Can view workflow pattern');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (25,7,'add_employeemaintenance','Can add employee maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (26,7,'change_employeemaintenance','Can change employee maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (27,7,'delete_employeemaintenance','Can delete employee maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (28,7,'view_employeemaintenance','Can view employee maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (29,8,'add_paymenttermmaintenance','Can add payment term maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (30,8,'change_paymenttermmaintenance','Can change payment term maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (31,8,'delete_paymenttermmaintenance','Can delete payment term maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (32,8,'view_paymenttermmaintenance','Can view payment term maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (33,9,'add_usermaintenance','Can add user maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (34,9,'change_usermaintenance','Can change user maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (35,9,'delete_usermaintenance','Can delete user maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (36,9,'view_usermaintenance','Can view user maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (37,10,'add_itemclassesmaintenance','Can add item classes maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (38,10,'change_itemclassesmaintenance','Can change item classes maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (39,10,'delete_itemclassesmaintenance','Can delete item classes maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (40,10,'view_itemclassesmaintenance','Can view item classes maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (41,11,'add_itemgroupsmaintenance','Can add item groups maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (42,11,'change_itemgroupsmaintenance','Can change item groups maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (43,11,'delete_itemgroupsmaintenance','Can delete item groups maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (44,11,'view_itemgroupsmaintenance','Can view item groups maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (45,12,'add_locationmaintenance','Can add location maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (46,12,'change_locationmaintenance','Can change location maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (47,12,'delete_locationmaintenance','Can delete location maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (48,12,'view_locationmaintenance','Can view location maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (49,13,'add_currencymaintenance','Can add currency maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (50,13,'change_currencymaintenance','Can change currency maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (51,13,'delete_currencymaintenance','Can delete currency maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (52,13,'view_currencymaintenance','Can view currency maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (53,14,'add_documenttypemaintenance','Can add document type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (54,14,'change_documenttypemaintenance','Can change document type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (55,14,'delete_documenttypemaintenance','Can delete document type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (56,14,'view_documenttypemaintenance','Can view document type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (57,15,'add_workflowapprovalrule','Can add workflow approval rule');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (58,15,'change_workflowapprovalrule','Can change workflow approval rule');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (59,15,'delete_workflowapprovalrule','Can delete workflow approval rule');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (60,15,'view_workflowapprovalrule','Can view workflow approval rule');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (61,16,'add_branchmaintenance','Can add branch maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (62,16,'change_branchmaintenance','Can change branch maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (63,16,'delete_branchmaintenance','Can delete branch maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (64,16,'view_branchmaintenance','Can view branch maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (65,17,'add_countrymaintenance','Can add country maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (66,17,'change_countrymaintenance','Can change country maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (67,17,'delete_countrymaintenance','Can delete country maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (68,17,'view_countrymaintenance','Can view country maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (69,18,'add_employeegroupmaintenance','Can add employee group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (70,18,'change_employeegroupmaintenance','Can change employee group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (71,18,'delete_employeegroupmaintenance','Can delete employee group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (72,18,'view_employeegroupmaintenance','Can view employee group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (73,19,'add_employeepositionmaintenance','Can add employee position maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (74,19,'change_employeepositionmaintenance','Can change employee position maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (75,19,'delete_employeepositionmaintenance','Can delete employee position maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (76,19,'view_employeepositionmaintenance','Can view employee position maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (77,20,'add_regionmaintenance','Can add region maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (78,20,'change_regionmaintenance','Can change region maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (79,20,'delete_regionmaintenance','Can delete region maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (80,20,'view_regionmaintenance','Can view region maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (81,21,'add_systemflagmaintenance','Can add system flag maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (82,21,'change_systemflagmaintenance','Can change system flag maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (83,21,'delete_systemflagmaintenance','Can delete system flag maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (84,21,'view_systemflagmaintenance','Can view system flag maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (85,22,'add_vendorgroupmaintenance','Can add vendor group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (86,22,'change_vendorgroupmaintenance','Can change vendor group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (87,22,'delete_vendorgroupmaintenance','Can delete vendor group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (88,22,'view_vendorgroupmaintenance','Can view vendor group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (89,23,'add_employeeprojectmaintenance','Can add employee project maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (90,23,'change_employeeprojectmaintenance','Can change employee project maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (91,23,'delete_employeeprojectmaintenance','Can delete employee project maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (92,23,'view_employeeprojectmaintenance','Can view employee project maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (93,24,'add_employeedepartmentmaintenance','Can add employee department maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (94,24,'change_employeedepartmentmaintenance','Can change employee department maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (95,24,'delete_employeedepartmentmaintenance','Can delete employee department maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (96,24,'view_employeedepartmentmaintenance','Can view employee department maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (97,25,'add_employeebranchmaintenance','Can add employee branch maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (98,25,'change_employeebranchmaintenance','Can change employee branch maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (99,25,'delete_employeebranchmaintenance','Can delete employee branch maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (100,25,'view_employeebranchmaintenance','Can view employee branch maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (101,26,'add_taxmaintenance','Can add tax maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (102,26,'change_taxmaintenance','Can change tax maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (103,26,'delete_taxmaintenance','Can delete tax maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (104,26,'view_taxmaintenance','Can view tax maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (105,27,'add_vendormasterdata','Can add vendor master data');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (106,27,'change_vendormasterdata','Can change vendor master data');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (107,27,'delete_vendormasterdata','Can delete vendor master data');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (108,27,'view_vendormasterdata','Can view vendor master data');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (109,28,'add_workflowapprovalgroup','Can add workflow approval group');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (110,28,'change_workflowapprovalgroup','Can change workflow approval group');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (111,28,'delete_workflowapprovalgroup','Can delete workflow approval group');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (112,28,'view_workflowapprovalgroup','Can view workflow approval group');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (113,29,'add_workflowapprovalrulegroupmaintenance','Can add workflow approval rule group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (114,29,'change_workflowapprovalrulegroupmaintenance','Can change workflow approval rule group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (115,29,'delete_workflowapprovalrulegroupmaintenance','Can delete workflow approval rule group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (116,29,'view_workflowapprovalrulegroupmaintenance','Can view workflow approval rule group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (117,30,'add_drawermaintenance','Can add drawer maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (118,30,'change_drawermaintenance','Can change drawer maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (119,30,'delete_drawermaintenance','Can delete drawer maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (120,30,'view_drawermaintenance','Can view drawer maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (121,31,'add_item','Can add Item Master Data');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (122,31,'change_item','Can change Item Master Data');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (123,31,'delete_item','Can delete Item Master Data');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (124,31,'view_item','Can view Item Master Data');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (125,32,'add_memo','Can add Memo');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (126,32,'change_memo','Can change Memo');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (127,32,'delete_memo','Can delete Memo');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (128,32,'view_memo','Can view Memo');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (129,33,'add_memoattachment','Can add Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (130,33,'change_memoattachment','Can change Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (131,33,'delete_memoattachment','Can delete Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (132,33,'view_memoattachment','Can view Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (133,34,'add_purchaserequest','Can add Purchase Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (134,34,'change_purchaserequest','Can change Purchase Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (135,34,'delete_purchaserequest','Can delete Purchase Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (136,34,'view_purchaserequest','Can view Purchase Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (137,35,'add_requestforquotation','Can add Request For Quotation');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (138,35,'change_requestforquotation','Can change Request For Quotation');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (139,35,'delete_requestforquotation','Can delete Request For Quotation');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (140,35,'view_requestforquotation','Can view Request For Quotation');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (141,36,'add_purchasequotation','Can add Purchase Quotation');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (142,36,'change_purchasequotation','Can change Purchase Quotation');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (143,36,'delete_purchasequotation','Can delete Purchase Quotation');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (144,36,'view_purchasequotation','Can view Purchase Quotation');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (145,37,'add_purchaseorder','Can add Purchase Order');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (146,37,'change_purchaseorder','Can change Purchase Order');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (147,37,'delete_purchaseorder','Can delete Purchase Order');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (148,37,'view_purchaseorder','Can view Purchase Order');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (149,38,'add_goodsreceiptnote','Can add Goods Receipt Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (150,38,'change_goodsreceiptnote','Can change Goods Receipt Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (151,38,'delete_goodsreceiptnote','Can delete Goods Receipt Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (152,38,'view_goodsreceiptnote','Can view Goods Receipt Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (153,39,'add_purchaseorderdetail','Can add Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (154,39,'change_purchaseorderdetail','Can change Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (155,39,'delete_purchaseorderdetail','Can delete Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (156,39,'view_purchaseorderdetail','Can view Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (157,40,'add_purchaseordercc','Can add CC');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (158,40,'change_purchaseordercc','Can change CC');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (159,40,'delete_purchaseordercc','Can delete CC');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (160,40,'view_purchaseordercc','Can view CC');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (161,41,'add_purchaseorderaddress','Can add Address');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (162,41,'change_purchaseorderaddress','Can change Address');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (163,41,'delete_purchaseorderaddress','Can delete Address');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (164,41,'view_purchaseorderaddress','Can view Address');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (165,42,'add_purchaserequestdetail','Can add Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (166,42,'change_purchaserequestdetail','Can change Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (167,42,'delete_purchaserequestdetail','Can delete Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (168,42,'view_purchaserequestdetail','Can view Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (169,43,'add_purchaserequestcc','Can add CC');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (170,43,'change_purchaserequestcc','Can change CC');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (171,43,'delete_purchaserequestcc','Can delete CC');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (172,43,'view_purchaserequestcc','Can view CC');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (173,44,'add_purchaserequestaddress','Can add Address');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (174,44,'change_purchaserequestaddress','Can change Address');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (175,44,'delete_purchaserequestaddress','Can delete Address');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (176,44,'view_purchaserequestaddress','Can view Address');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (177,45,'add_purchaserequestpettycash','Can add Purchase Request (Petty Cash)');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (178,45,'change_purchaserequestpettycash','Can change Purchase Request (Petty Cash)');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (179,45,'delete_purchaserequestpettycash','Can delete Purchase Request (Petty Cash)');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (180,45,'view_purchaserequestpettycash','Can view Purchase Request (Petty Cash)');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (181,46,'add_purchaserequestpettycashitems','Can add Item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (182,46,'change_purchaserequestpettycashitems','Can change Item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (183,46,'delete_purchaserequestpettycashitems','Can delete Item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (184,46,'view_purchaserequestpettycashitems','Can view Item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (185,47,'add_logentry','Can add log entry');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (186,47,'change_logentry','Can change log entry');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (187,47,'delete_logentry','Can delete log entry');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (188,47,'view_logentry','Can view log entry');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (189,48,'add_permission','Can add permission');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (190,48,'change_permission','Can change permission');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (191,48,'delete_permission','Can delete permission');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (192,48,'view_permission','Can view permission');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (193,49,'add_group','Can add group');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (194,49,'change_group','Can change group');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (195,49,'delete_group','Can delete group');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (196,49,'view_group','Can view group');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (197,50,'add_user','Can add user');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (198,50,'change_user','Can change user');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (199,50,'delete_user','Can delete user');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (200,50,'view_user','Can view user');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (201,51,'add_contenttype','Can add content type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (202,51,'change_contenttype','Can change content type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (203,51,'delete_contenttype','Can delete content type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (204,51,'view_contenttype','Can view content type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (205,52,'add_session','Can add session');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (206,52,'change_session','Can change session');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (207,52,'delete_session','Can delete session');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (208,52,'view_session','Can view session');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (209,53,'add_paymentrequest','Can add Payment Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (210,53,'change_paymentrequest','Can change Payment Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (211,53,'delete_paymentrequest','Can delete Payment Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (212,53,'view_paymentrequest','Can view Payment Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (213,54,'add_transactiontypemaintenance','Can add transactiontype maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (214,54,'change_transactiontypemaintenance','Can change transactiontype maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (215,54,'delete_transactiontypemaintenance','Can delete transactiontype maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (216,54,'view_transactiontypemaintenance','Can view transactiontype maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (217,55,'add_paymentmodemaintenance','Can add paymentmode maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (218,55,'change_paymentmodemaintenance','Can change paymentmode maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (219,55,'delete_paymentmodemaintenance','Can delete paymentmode maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (220,55,'view_paymentmodemaintenance','Can view paymentmode maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (221,56,'add_memotemplatemaintenance','Can add memo template maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (222,56,'change_memotemplatemaintenance','Can change memo template maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (223,56,'delete_memotemplatemaintenance','Can delete memo template maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (224,56,'view_memotemplatemaintenance','Can view memo template maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (225,57,'add_paymentrequestdetail','Can add Payment Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (226,57,'change_paymentrequestdetail','Can change Payment Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (227,57,'delete_paymentrequestdetail','Can delete Payment Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (228,57,'view_paymentrequestdetail','Can view Payment Detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (229,58,'add_uommaintenance','Can add uom maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (230,58,'change_uommaintenance','Can change uom maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (231,58,'delete_uommaintenance','Can delete uom maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (232,58,'view_uommaintenance','Can view uom maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (233,59,'add_displayfield','Can add display field');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (234,59,'change_displayfield','Can change display field');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (235,59,'delete_displayfield','Can delete display field');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (236,59,'view_displayfield','Can view display field');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (237,60,'add_filterfield','Can add filter field');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (238,60,'change_filterfield','Can change filter field');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (239,60,'delete_filterfield','Can delete filter field');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (240,60,'view_filterfield','Can view filter field');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (241,61,'add_format','Can add format');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (242,61,'change_format','Can change format');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (243,61,'delete_format','Can delete format');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (244,61,'view_format','Can view format');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (245,62,'add_report','Can add report');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (246,62,'change_report','Can change report');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (247,62,'delete_report','Can delete report');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (248,62,'view_report','Can view report');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (249,63,'add_paymentattachment','Can add Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (250,63,'change_paymentattachment','Can change Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (251,63,'delete_paymentattachment','Can delete Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (252,63,'view_paymentattachment','Can view Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (253,64,'add_itemcategorymaintenance','Can add item category maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (254,64,'change_itemcategorymaintenance','Can change item category maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (255,64,'delete_itemcategorymaintenance','Can delete item category maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (256,64,'view_itemcategorymaintenance','Can view item category maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (257,65,'add_statemaintenance','Can add state maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (258,65,'change_statemaintenance','Can change state maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (259,65,'delete_statemaintenance','Can delete state maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (260,65,'view_statemaintenance','Can view state maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (261,66,'add_vendorcontactdetail','Can add vendor contact detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (262,66,'change_vendorcontactdetail','Can change vendor contact detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (263,66,'delete_vendorcontactdetail','Can delete vendor contact detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (264,66,'view_vendorcontactdetail','Can view vendor contact detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (265,67,'add_vendoraddressdetail','Can add vendor address detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (266,67,'change_vendoraddressdetail','Can change vendor address detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (267,67,'delete_vendoraddressdetail','Can delete vendor address detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (268,67,'view_vendoraddressdetail','Can view vendor address detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (269,68,'add_vendorcategorymaintenance','Can add vendor category maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (270,68,'change_vendorcategorymaintenance','Can change vendor category maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (271,68,'delete_vendorcategorymaintenance','Can delete vendor category maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (272,68,'view_vendorcategorymaintenance','Can view vendor category maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (273,69,'add_companycontactdetail','Can add company contact detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (274,69,'change_companycontactdetail','Can change company contact detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (275,69,'delete_companycontactdetail','Can delete company contact detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (276,69,'view_companycontactdetail','Can view company contact detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (277,70,'add_companyaddressdetail','Can add company address detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (278,70,'change_companyaddressdetail','Can change company address detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (279,70,'delete_companyaddressdetail','Can delete company address detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (280,70,'view_companyaddressdetail','Can view company address detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (281,71,'add_staffrecruitmentrequest','Can add Staff Recruitment Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (282,71,'change_staffrecruitmentrequest','Can change Staff Recruitment Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (283,71,'delete_staffrecruitmentrequest','Can delete Staff Recruitment Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (284,71,'view_staffrecruitmentrequest','Can view Staff Recruitment Request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (285,72,'add_utiliyaccounttypemaintenance','Can add utiliy account type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (286,72,'change_utiliyaccounttypemaintenance','Can change utiliy account type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (287,72,'delete_utiliyaccounttypemaintenance','Can delete utiliy account type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (288,72,'view_utiliyaccounttypemaintenance','Can view utiliy account type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (289,73,'add_staffpositiontitlemaintenance','Can add staff position title maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (290,73,'change_staffpositiontitlemaintenance','Can change staff position title maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (291,73,'delete_staffpositiontitlemaintenance','Can delete staff position title maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (292,73,'view_staffpositiontitlemaintenance','Can view staff position title maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (293,74,'add_staffhiretypemaintenance','Can add staff hire type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (294,74,'change_staffhiretypemaintenance','Can change staff hire type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (295,74,'delete_staffhiretypemaintenance','Can delete staff hire type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (296,74,'view_staffhiretypemaintenance','Can view staff hire type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (297,75,'add_staffjobrequirement','Can add staff job requirement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (298,75,'change_staffjobrequirement','Can change staff job requirement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (299,75,'delete_staffjobrequirement','Can delete staff job requirement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (300,75,'view_staffjobrequirement','Can view staff job requirement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (301,76,'add_staffjobresponsibilities','Can add staff job responsibilities');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (302,76,'change_staffjobresponsibilities','Can change staff job responsibilities');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (303,76,'delete_staffjobresponsibilities','Can delete staff job responsibilities');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (304,76,'view_staffjobresponsibilities','Can view staff job responsibilities');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (305,77,'add_approvalitem','Can add approval item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (306,77,'change_approvalitem','Can change approval item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (307,77,'delete_approvalitem','Can delete approval item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (308,77,'view_approvalitem','Can view approval item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (309,78,'add_approvalitemcc','Can add approval item cc');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (310,78,'change_approvalitemcc','Can change approval item cc');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (311,78,'delete_approvalitemcc','Can delete approval item cc');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (312,78,'view_approvalitemcc','Can view approval item cc');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (313,79,'add_approvalitemapprover','Can add approval item approver');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (314,79,'change_approvalitemapprover','Can change approval item approver');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (315,79,'delete_approvalitemapprover','Can delete approval item approver');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (316,79,'view_approvalitemapprover','Can view approval item approver');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (317,74,'add_staffemploymenttypemaintenance','Can add staffemployment type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (318,74,'change_staffemploymenttypemaintenance','Can change staffemployment type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (319,74,'delete_staffemploymenttypemaintenance','Can delete staffemployment type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (320,74,'view_staffemploymenttypemaintenance','Can view staffemployment type maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (321,80,'add_staffpositiongrademaintenance','Can add staff position grade maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (322,80,'change_staffpositiongrademaintenance','Can change staff position grade maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (323,80,'delete_staffpositiongrademaintenance','Can delete staff position grade maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (324,80,'view_staffpositiongrademaintenance','Can view staff position grade maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (325,81,'add_drawerusermaintenance','Can add drawer user maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (326,81,'change_drawerusermaintenance','Can change drawer user maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (327,81,'delete_drawerusermaintenance','Can delete drawer user maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (328,81,'view_drawerusermaintenance','Can view drawer user maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (329,82,'add_drawerdisbursement','Can add drawer disbursement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (330,82,'change_drawerdisbursement','Can change drawer disbursement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (331,82,'delete_drawerdisbursement','Can delete drawer disbursement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (332,82,'view_drawerdisbursement','Can view drawer disbursement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (333,83,'add_purchaseorderattachment','Can add Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (334,83,'change_purchaseorderattachment','Can change Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (335,83,'delete_purchaseorderattachment','Can delete Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (336,83,'view_purchaseorderattachment','Can view Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (337,84,'add_purchaseordercomparison2attachment','Can add Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (338,84,'change_purchaseordercomparison2attachment','Can change Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (339,84,'delete_purchaseordercomparison2attachment','Can delete Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (340,84,'view_purchaseordercomparison2attachment','Can view Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (341,85,'add_purchaseordercomparison3attachment','Can add Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (342,85,'change_purchaseordercomparison3attachment','Can change Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (343,85,'delete_purchaseordercomparison3attachment','Can delete Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (344,85,'view_purchaseordercomparison3attachment','Can view Attachment');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (345,86,'add_tax','Can add tax');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (346,86,'change_tax','Can change tax');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (347,86,'delete_tax','Can delete tax');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (348,86,'view_tax','Can view tax');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (349,87,'add_classtype','Can add class type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (350,87,'change_classtype','Can change class type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (351,87,'delete_classtype','Can delete class type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (352,87,'view_classtype','Can view class type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (353,88,'add_assetmaster','Can add asset master');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (354,88,'change_assetmaster','Can change asset master');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (355,88,'delete_assetmaster','Can delete asset master');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (356,88,'view_assetmaster','Can view asset master');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (357,89,'add_assetcategory','Can add asset category');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (358,89,'change_assetcategory','Can change asset category');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (359,89,'delete_assetcategory','Can delete asset category');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (360,89,'view_assetcategory','Can view asset category');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (361,90,'add_statistics','Can add statistics');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (362,90,'change_statistics','Can change statistics');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (363,90,'delete_statistics','Can delete statistics');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (364,90,'view_statistics','Can view statistics');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (365,91,'add_assettype','Can add asset type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (366,91,'change_assettype','Can change asset type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (367,91,'delete_assettype','Can delete asset type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (368,91,'view_assettype','Can view asset type');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (369,92,'add_employeecompanymaintenance','Can add employee company maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (370,92,'change_employeecompanymaintenance','Can change employee company maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (371,92,'delete_employeecompanymaintenance','Can delete employee company maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (372,92,'view_employeecompanymaintenance','Can view employee company maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (373,93,'add_otratemaintenance','Can add ot rate maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (374,93,'change_otratemaintenance','Can change ot rate maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (375,93,'delete_otratemaintenance','Can delete ot rate maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (376,93,'view_otratemaintenance','Can view ot rate maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (377,94,'add_holidayeventmaintenance','Can add holiday event maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (378,94,'change_holidayeventmaintenance','Can change holiday event maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (379,94,'delete_holidayeventmaintenance','Can delete holiday event maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (380,94,'view_holidayeventmaintenance','Can view holiday event maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (381,95,'add_purchaseinvoice','Can add Purchase Invoice');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (382,95,'change_purchaseinvoice','Can change Purchase Invoice');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (383,95,'delete_purchaseinvoice','Can delete Purchase Invoice');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (384,95,'view_purchaseinvoice','Can view Purchase Invoice');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (385,96,'add_purchasedebitnote','Can add Credit Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (386,96,'change_purchasedebitnote','Can change Credit Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (387,96,'delete_purchasedebitnote','Can delete Credit Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (388,96,'view_purchasedebitnote','Can view Credit Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (389,97,'add_purchasecreditnote','Can add Credit Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (390,97,'change_purchasecreditnote','Can change Credit Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (391,97,'delete_purchasecreditnote','Can delete Credit Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (392,97,'view_purchasecreditnote','Can view Credit Note');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (393,98,'add_staffot','Can add Staff OT');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (394,98,'change_staffot','Can change Staff OT');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (395,98,'delete_staffot','Can delete Staff OT');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (396,98,'view_staffot','Can view Staff OT');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (397,99,'add_staffotdetail','Can add staff ot detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (398,99,'change_staffotdetail','Can change staff ot detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (399,99,'delete_staffotdetail','Can delete staff ot detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (400,99,'view_staffotdetail','Can view staff ot detail');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (401,100,'add_advancerefund','Can add Advance Refund');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (402,100,'change_advancerefund','Can change Advance Refund');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (403,100,'delete_advancerefund','Can delete Advance Refund');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (404,100,'view_advancerefund','Can view Advance Refund');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (405,101,'add_reimbursementrequest','Can add reimbursement request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (406,101,'change_reimbursementrequest','Can change reimbursement request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (407,101,'delete_reimbursementrequest','Can delete reimbursement request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (408,101,'view_reimbursementrequest','Can view reimbursement request');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (409,102,'add_utiliygroupmaintenance','Can add utiliy group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (410,102,'change_utiliygroupmaintenance','Can change utiliy group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (411,102,'delete_utiliygroupmaintenance','Can delete utiliy group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (412,102,'view_utiliygroupmaintenance','Can view utiliy group maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (413,103,'add_hrplatformmaintenance','Can add hr platform maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (414,103,'change_hrplatformmaintenance','Can change hr platform maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (415,103,'delete_hrplatformmaintenance','Can delete hr platform maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (416,103,'view_hrplatformmaintenance','Can view hr platform maintenance');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (417,104,'add_staffplatform','Can add staff platform');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (418,104,'change_staffplatform','Can change staff platform');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (419,104,'delete_staffplatform','Can delete staff platform');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (420,104,'view_staffplatform','Can view staff platform');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (421,105,'add_staffcandidate','Can add staff candidate');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (422,105,'change_staffcandidate','Can change staff candidate');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (423,105,'delete_staffcandidate','Can delete staff candidate');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (424,105,'view_staffcandidate','Can view staff candidate');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (425,106,'add_drawerreimbursement','Can add drawer reimbursement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (426,106,'change_drawerreimbursement','Can change drawer reimbursement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (427,106,'delete_drawerreimbursement','Can delete drawer reimbursement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (428,106,'view_drawerreimbursement','Can view drawer reimbursement');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (429,107,'add_utilityapprovalitem','Can add utility approval item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (430,107,'change_utilityapprovalitem','Can change utility approval item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (431,107,'delete_utilityapprovalitem','Can delete utility approval item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (432,107,'view_utilityapprovalitem','Can view utility approval item');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (433,108,'add_utilityapprovalitemcc','Can add utility approval item cc');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (434,108,'change_utilityapprovalitemcc','Can change utility approval item cc');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (435,108,'delete_utilityapprovalitemcc','Can delete utility approval item cc');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (436,108,'view_utilityapprovalitemcc','Can view utility approval item cc');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (437,109,'add_utilityapprovalitemapprover','Can add utility approval item approver');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (438,109,'change_utilityapprovalitemapprover','Can change utility approval item approver');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (439,109,'delete_utilityapprovalitemapprover','Can delete utility approval item approver');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (440,109,'view_utilityapprovalitemapprover','Can view utility approval item approver');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (441,110,'add_accounttask','Can add account task');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (442,110,'change_accounttask','Can change account task');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (443,110,'delete_accounttask','Can delete account task');
INSERT INTO "auth_permission" ("id","content_type_id","codename","name") VALUES (444,110,'view_accounttask','Can view account task');
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (4,2,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (5,3,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (6,4,2);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (7,5,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (8,6,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (9,7,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (10,8,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (11,9,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (12,10,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (13,11,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (14,12,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (15,13,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (16,14,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (17,15,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (18,16,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (19,17,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (20,18,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (21,19,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (22,20,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (23,21,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (24,22,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (25,23,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (26,24,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (27,25,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (28,26,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (29,27,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (30,28,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (31,29,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (32,30,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (33,31,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (34,32,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (35,33,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (36,34,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (37,35,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (38,36,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (39,37,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (40,38,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (41,39,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (42,40,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (43,41,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (44,42,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (45,43,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (46,44,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (47,45,2);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (48,46,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (49,47,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (50,48,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (51,49,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (52,50,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (53,51,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (54,52,2);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (55,53,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (56,54,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (57,55,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (58,56,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (59,57,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (60,58,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (61,59,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (62,60,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (63,61,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (64,62,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (65,63,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (66,64,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (67,65,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (68,66,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (69,67,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (70,68,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (71,69,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (72,70,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (73,71,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (74,72,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (75,73,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (76,74,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (77,75,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (78,76,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (79,77,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (80,78,2);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (81,79,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (82,80,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (83,81,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (84,82,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (85,83,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (86,84,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (87,85,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (88,86,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (89,87,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (90,88,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (91,89,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (92,90,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (93,91,2);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (94,92,2);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (95,93,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (96,94,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (97,95,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (98,96,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (99,97,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (100,98,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (101,99,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (102,100,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (103,101,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (104,102,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (105,103,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (106,104,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (107,105,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (108,106,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (109,107,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (110,108,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (111,109,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (112,110,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (113,111,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (114,112,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (115,113,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (116,114,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (117,115,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (118,116,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (119,117,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (120,118,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (121,119,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (122,120,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (123,121,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (124,122,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (125,123,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (126,124,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (127,125,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (128,126,1);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (129,127,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (130,128,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (131,129,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (132,130,3);
INSERT INTO "auth_user_groups" ("id","user_id","group_id") VALUES (133,131,3);
CREATE INDEX IF NOT EXISTS "auth_permission_content_type_id_2f476e4b" ON "auth_permission" (
	"content_type_id"
);
CREATE UNIQUE INDEX IF NOT EXISTS "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" (
	"content_type_id",
	"codename"
);
CREATE INDEX IF NOT EXISTS "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" (
	"permission_id"
);
CREATE INDEX IF NOT EXISTS "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" (
	"user_id"
);
CREATE UNIQUE INDEX IF NOT EXISTS "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" (
	"user_id",
	"permission_id"
);
CREATE INDEX IF NOT EXISTS "auth_user_groups_group_id_97559544" ON "auth_user_groups" (
	"group_id"
);
CREATE INDEX IF NOT EXISTS "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" (
	"user_id"
);
CREATE UNIQUE INDEX IF NOT EXISTS "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" (
	"user_id",
	"group_id"
);
CREATE INDEX IF NOT EXISTS "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" (
	"permission_id"
);
CREATE INDEX IF NOT EXISTS "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" (
	"group_id"
);
CREATE UNIQUE INDEX IF NOT EXISTS "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" (
	"group_id",
	"permission_id"
);
COMMIT;
