# Generated by Django 3.0.3 on 2020-04-01 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0024_merge_20200331_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawerDisbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1)),
                ('total_disbursed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disbursed_date', models.DateField(auto_now_add=True)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentRequest', verbose_name='Payment Request')),
            ],
        ),
    ]
