# Generated by Django 3.0.3 on 2020-04-03 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0062_drawerusermaintenance'),
        ('drawer_disbursement', '0002_drawerdisbursement_drawer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawerdisbursement',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.StatusMaintenance'),
        ),
    ]
