# Generated by Django 3.0.3 on 2020-03-17 01:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='attachment',
            field=models.FileField(default='', upload_to='', verbose_name='File Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='attachment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='MemoCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.Memo')),
            ],
            options={
                'verbose_name': 'CC',
            },
        ),
    ]
