# Generated by Django 3.0.3 on 2020-03-23 02:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_auto_20200317_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='', verbose_name='File Name')),
                ('attachment_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attachment',
            },
        ),
        migrations.RemoveField(
            model_name='memo',
            name='attachment_date',
        ),
        migrations.AlterField(
            model_name='memo',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='memo',
            name='submit_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='MemoCC',
        ),
        migrations.AlterField(
            model_name='memo',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.MemoAttachment', verbose_name='Attachment'),
        ),
    ]
