# Generated by Django 3.0.3 on 2020-03-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0039_employeemaintenance_employee_signature'),
        ('memo', '0003_auto_20200323_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.MemoTemplateMaintenance', verbose_name='Project'),
            preserve_default=False,
        ),
    ]
