# Generated by Django 3.0.3 on 2020-03-24 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_memo_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='attachment',
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='memo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='memo.Memo', verbose_name='Memo'),
            preserve_default=False,
        ),
    ]
