# Generated by Django 3.0.3 on 2020-03-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0007_auto_20200326_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='revision',
            field=models.IntegerField(default=0),
        ),
    ]
