# Generated by Django 3.0.3 on 2020-03-28 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
        ('memo', '0008_auto_20200328_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalItem', verbose_name='Project'),
        ),
    ]
