# Generated by Django 3.0.3 on 2020-03-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0010_auto_20200328_1232'),
        ('memo', '0008_auto_20200326_1531'),
    ]

    operations = [
    ]
