# Generated by Django 3.0.3 on 2020-03-29 04:37

from django.db import migrations, models
import memo.models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0011_merge_20200329_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='revision',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='memoattachment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=memo.models.documenttype_directory_path, verbose_name='File Name'),
        ),
    ]
