# Generated by Django 3.0.3 on 2020-03-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0013_auto_20200330_0035'),
        ('memo', '0012_auto_20200329_1237'),
    ]

    operations = [
    ]
