# Generated by Django 3.0.3 on 2020-03-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0014_merge_20200330_1010'),
        ('memo', '0014_merge_20200330_1034'),
    ]

    operations = [
    ]
