# Generated by Django 3.0.4 on 2020-04-02 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0061_staffpositiongrademaintenance'),
        ('approval', '0004_auto_20200331_0251'),
        ('memo', '0015_merge_20200331_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalItem'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.ProjectMaintenance', verbose_name='Project'),
        ),
    ]
