# Generated by Django 3.0.3 on 2020-04-02 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_auto_20200331_0251'),
        ('memo', '0015_merge_20200331_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalItem'),
        ),
    ]
