# Generated by Django 3.0.4 on 2020-04-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0016_auto_20200402_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
