# Generated by Django 3.0.4 on 2020-04-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0017_auto_20200402_0558'),
        ('memo', '0017_auto_20200402_1439'),
    ]

    operations = [
    ]
