# Generated by Django 3.0.4 on 2020-04-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0018_merge_20200402_1736'),
        ('memo', '0018_merge_20200402_0749'),
    ]

    operations = [
    ]
