# Generated by Django 3.0.4 on 2020-04-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0062_drawerusermaintenance'),
        ('memo', '0019_merge_20200403_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.StatusMaintenance'),
        ),
    ]
