# Generated by Django 3.0.4 on 2020-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0020_auto_20200403_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. No.'),
        ),
    ]
