# Generated by Django 3.0.3 on 2020-03-17 00:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20200225_1558'),
        ('purchasing', '0002_goodsreceiptnote_purchaseorder_purchasequotation_requestforquotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='attachment',
            field=models.FileField(upload_to='', verbose_name='File Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='attachment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_schedule',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_term',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='remarks',
            field=models.CharField(max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Additional Description')),
                ('quantity', models.IntegerField(verbose_name='Qty')),
                ('amount', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Item', verbose_name='Item')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseOrder')),
            ],
            options={
                'verbose_name': 'Detail',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseOrder')),
            ],
            options={
                'verbose_name': 'CC',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Pay To')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseOrder')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
