# Generated by Django 3.0.3 on 2020-03-17 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_auto_20200311_1814'),
        ('purchasing', '0004_auto_20200317_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestPettyCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_employee', models.BooleanField(verbose_name='Pay To')),
                ('revision', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('submit_date', models.DateField()),
                ('payment_mode', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=250)),
                ('reference', models.CharField(max_length=100)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remarks', models.CharField(max_length=250)),
                ('attachment', models.FileField(upload_to='', verbose_name='File Name')),
                ('attachment_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CurrencyMaintenance', verbose_name='Currency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeMaintenance', verbose_name='Requester')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ProjectMaintenance', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Purchase Request (Petty Cash)',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestPettyCashItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Item Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseRequestPettyCash')),
            ],
            options={
                'verbose_name': 'Item',
            },
        ),
    ]
