# Generated by Django 3.0.3 on 2020-03-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_purchaserequestpettycash_purchaserequestpettycashitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestpettycash',
            options={'verbose_name': 'Purchase Request (Petty Cash)', 'verbose_name_plural': 'Purchase Request (Petty Cash)'},
        ),
    ]
