# Generated by Django 3.0.3 on 2020-03-22 18:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_auto_20200319_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='remarks',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
