# Generated by Django 3.0.3 on 2020-03-30 21:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import purchasing.models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_auto_20200331_0251'),
        ('administration', '0059_auto_20200331_0248'),
        ('purchasing', '0008_auto_20200323_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalItem', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='document_number',
            field=models.CharField(blank=True, default=purchasing.models.documenttype_document_number, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='remarks',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='revision',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, default='D', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='submit_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeMaintenance', verbose_name='Vendor'),
        ),
    ]
