# Generated by Django 3.0.4 on 2020-04-01 06:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0061_staffpositiongrademaintenance'),
        ('purchasing', '0011_auto_20200331_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='attachment_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='administration.VendorAddressDetail'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='billing_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing', to='administration.VendorMasterData', verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_address', to='administration.VendorAddressDetail'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_instruction',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='administration.VendorMasterData', verbose_name='Delivery Address'),
        ),
    ]
