# Generated by Django 3.0.4 on 2020-04-01 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0061_staffpositiongrademaintenance'),
        ('purchasing', '0012_auto_20200401_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='billing_vendor',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_vendor',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='billing_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing', to='administration.CompanyMaintenance', verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='administration.CompanyMaintenance', verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='billing_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
