# Generated by Django 3.0.4 on 2020-04-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0013_auto_20200401_0740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrderAddress',
        ),
    ]
