# Generated by Django 3.0.4 on 2020-04-01 14:31

from django.db import migrations, models
import django.db.models.deletion
import purchasing.models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0061_staffpositiongrademaintenance'),
        ('purchasing', '0016_purchaseorder_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=purchasing.models.documenttype_directory_path, verbose_name='File Name')),
                ('attachment_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attachment',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderComparison2Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=purchasing.models.documenttype_directory_path, verbose_name='File Name')),
                ('attachment_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attachment',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderComparison3Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=purchasing.models.documenttype_directory_path, verbose_name='File Name')),
                ('attachment_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attachment',
            },
        ),
        migrations.RemoveField(
            model_name='purchasequotation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='purchasequotation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='purchasequotation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='purchasequotation',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='company',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='purchaserequestaddress',
            name='pr',
        ),
        migrations.RemoveField(
            model_name='purchaserequestcc',
            name='pr',
        ),
        migrations.RemoveField(
            model_name='purchaserequestdetail',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaserequestdetail',
            name='pr',
        ),
        migrations.RemoveField(
            model_name='purchaserequestpettycash',
            name='company',
        ),
        migrations.RemoveField(
            model_name='purchaserequestpettycash',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='purchaserequestpettycash',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='purchaserequestpettycash',
            name='project',
        ),
        migrations.RemoveField(
            model_name='purchaserequestpettycashitems',
            name='prpc',
        ),
        migrations.RemoveField(
            model_name='requestforquotation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='requestforquotation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='requestforquotation',
            name='requester',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='comparison_vendor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison2', to='administration.VendorMasterData', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='comparison_vendor_2_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='comparison_vendor_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison3', to='administration.VendorMasterData', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='comparison_vendor_3_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderCC',
        ),
        migrations.DeleteModel(
            name='PurchaseQuotation',
        ),
        migrations.DeleteModel(
            name='PurchaseRequest',
        ),
        migrations.DeleteModel(
            name='PurchaseRequestAddress',
        ),
        migrations.DeleteModel(
            name='PurchaseRequestCC',
        ),
        migrations.DeleteModel(
            name='PurchaseRequestDetail',
        ),
        migrations.DeleteModel(
            name='PurchaseRequestPettyCash',
        ),
        migrations.DeleteModel(
            name='PurchaseRequestPettyCashItems',
        ),
        migrations.DeleteModel(
            name='RequestForQuotation',
        ),
        migrations.AddField(
            model_name='purchaseordercomparison3attachment',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='purchaseordercomparison2attachment',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='purchaseorderattachment',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseOrder'),
        ),
    ]
