# Generated by Django 3.0.4 on 2020-04-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0061_staffpositiongrademaintenance'),
        ('Inventory', '0007_auto_20200327_1307'),
        ('purchasing', '0017_auto_20200401_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderdetail',
            name='discount',
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='additional_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Additional Description'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.UOMMaintenance', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='comparison_vendor_2_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='comparison_vendor_3_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Additional Description'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.Item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseOrder'),
        ),
    ]
