# Generated by Django 3.0.4 on 2020-04-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0018_auto_20200401_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderdetail',
            name='description',
        ),
    ]
