# Generated by Django 3.0.4 on 2020-04-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0019_remove_purchaseorderdetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount (%)'),
        ),
    ]
