# Generated by Django 3.0.4 on 2020-04-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0022_auto_20200402_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
