# Generated by Django 3.0.4 on 2020-04-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0063_auto_20200403_1652'),
        ('purchasing', '0023_purchaseorder_vendor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.StatusMaintenance'),
        ),
    ]
