# Generated by Django 3.0.4 on 2020-04-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0067_merge_20200405_0820'),
        ('purchasing', '0026_auto_20200406_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.PaymentTermMaintenance', verbose_name='Payment Term'),
        ),
    ]
