# Generated by Django 3.0.4 on 2020-04-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0069_workflowapprovalrulegroupmaintenance_submitter_group'),
        ('purchasing', '0027_auto_20200407_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.PaymentTermMaintenance', verbose_name='Payment Terms'),
        ),
    ]
