# Generated by Django 3.0.4 on 2020-04-13 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0028_auto_20200409_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='company',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='project',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='status',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='submit_date',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='supplier',
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='receive_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(auto_now_add=True, null=True)),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseOrder')),
            ],
            options={
                'verbose_name': 'Purchase Invoice',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDebitNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseOrder')),
            ],
            options={
                'verbose_name': 'Credit Note',
            },
        ),
        migrations.CreateModel(
            name='PurchaseCreditNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.PurchaseOrder')),
            ],
            options={
                'verbose_name': 'Credit Note',
            },
        ),
    ]
