# Generated by Django 3.0.5 on 2020-04-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0029_auto_20200413_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
