# Generated by Django 3.0.5 on 2020-04-20 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0071_auto_20200415_1448'),
        ('purchasing', '0030_auto_20200420_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='line_taxamount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.TaxMaintenance'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='tax_exclude',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='exclude tax'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='comparison_vendor_2_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='comparison_vendor_3_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
