# Generated by Django 3.0.5 on 2020-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0031_auto_20200420_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Qty'),
        ),
    ]
