# Generated by Django 3.0.5 on 2020-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0033_goodsreceiptnote_receive_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='receive_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
