# Generated by Django 3.0.5 on 2020-04-20 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchasing', '0034_auto_20200421_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='receive_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
