# Generated by Django 3.0.5 on 2020-04-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0035_purchaseinvoice_receive_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15, verbose_name='Qty'),
        ),
    ]
