# Generated by Django 3.0.5 on 2020-04-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0036_auto_20200421_1218'),
        ('purchasing', '0036_auto_20200421_1328'),
    ]

    operations = [
    ]
