# Generated by Django 3.0.3 on 2020-03-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0014_auto_20200310_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRecruitmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=100)),
                ('revision', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('budgeted', models.BooleanField()),
                ('status', models.CharField(max_length=1)),
                ('hire_type', models.CharField(max_length=1)),
                ('request_date', models.DateField()),
                ('subject', models.CharField(max_length=250)),
                ('reference', models.CharField(max_length=100)),
                ('headcounts', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company')),
                ('reporting_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeMaintenance', verbose_name='Reporting To')),
            ],
            options={
                'verbose_name': 'Staff Recruitment Request',
                'verbose_name_plural': 'Staff Recruitment Requests',
            },
        ),
    ]
