# Generated by Django 3.0.3 on 2020-03-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffrecruitmentrequest',
            old_name='headcounts',
            new_name='no_of_pax',
        ),
    ]
