# Generated by Django 3.0.3 on 2020-03-28 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resource', '0002_auto_20200328_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrecruitmentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffrecruitmentcreated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffrecruitmentrequest',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffrecruitmentrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffrecruitmentmodified_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffrecruitmentrequest',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
