# Generated by Django 3.0.3 on 2020-03-28 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0050_staffhiretypemaintenance_staffpositiontitlemaintenance_utiliyaccounttypemaintenance'),
        ('human_resource', '0003_auto_20200328_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrecruitmentrequest',
            name='reference',
        ),
        migrations.AddField(
            model_name='staffrecruitmentrequest',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.DepartmentMaintenance', verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffrecruitmentrequest',
            name='month_to_be_filled',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='position_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='subject',
            field=models.CharField(max_length=300),
        ),
    ]
