# Generated by Django 3.0.3 on 2020-03-28 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0005_auto_20200328_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffJobResponsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponsible_description', models.CharField(max_length=250)),
                ('staff_recruiment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.StaffRecruitmentRequest')),
            ],
        ),
        migrations.CreateModel(
            name='StaffJobRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_description', models.CharField(max_length=250)),
                ('staff_recruiment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.StaffRecruitmentRequest')),
            ],
        ),
    ]
