# Generated by Django 3.0.3 on 2020-03-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0006_staffjobrequirement_staffjobresponsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='document_number',
            field=models.CharField(max_length=100, verbose_name='Document No.'),
        ),
    ]
