# Generated by Django 3.0.3 on 2020-03-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0007_auto_20200328_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
