# Generated by Django 3.0.3 on 2020-03-31 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_auto_20200331_0251'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resource', '0011_auto_20200331_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrecruitmentrequest',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalItem', verbose_name='Approval'),
        ),
        migrations.AddField(
            model_name='staffrecruitmentrequest',
            name='submit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='status',
            field=models.CharField(blank=True, default='D', max_length=1, null=True),
        ),
    ]
