# Generated by Django 3.0.3 on 2020-03-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0014_auto_20200331_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffjobresponsibilities',
            old_name='reponsible_description',
            new_name='responsible_description',
        ),
    ]
