# Generated by Django 3.0.3 on 2020-03-31 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0015_auto_20200331_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffjobrequirement',
            name='staff_recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource.StaffRecruitmentRequest'),
        ),
        migrations.AlterField(
            model_name='staffjobresponsibilities',
            name='staff_recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource.StaffRecruitmentRequest'),
        ),
    ]
