# Generated by Django 3.0.3 on 2020-03-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0016_auto_20200331_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrecruitmentrequest',
            name='subject',
        ),
        migrations.AlterField(
            model_name='staffjobrequirement',
            name='requirement_description',
            field=models.CharField(max_length=250, verbose_name='Requirement'),
        ),
        migrations.AlterField(
            model_name='staffjobresponsibilities',
            name='responsible_description',
            field=models.CharField(max_length=250, verbose_name='Responsible'),
        ),
    ]
