# Generated by Django 3.0.3 on 2020-04-04 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import human_resource.models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0062_drawerusermaintenance'),
        ('human_resource', '0017_auto_20200331_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='budgeted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.DepartmentMaintenance', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Document No.'),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.StaffemploymentTypeMaintenance', verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='month_to_be_filled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='no_of_pax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='position_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.StaffPositionGradeMaintenance', verbose_name='Position Grade'),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='position_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.StaffPositionTitleMaintenance', verbose_name='Position Title'),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeMaintenance', verbose_name='Reporting To'),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='request_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='revision',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='status',
            field=models.ForeignKey(blank=True, default=human_resource.models.default_status, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.StatusMaintenance', verbose_name='Status'),
        ),
    ]
