# Generated by Django 3.0.5 on 2020-04-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0079_merge_20200426_0046'),
        ('human_resource', '0019_staffcandidate_staffplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecruitmentrequest',
            name='position_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeePositionMaintenance', verbose_name='Position Title'),
        ),
    ]
