# Generated by Django 3.0.3 on 2020-02-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('revision', models.IntegerField()),
                ('docno', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('submitDate', models.DateTimeField()),
            ],
        ),
    ]
