# Generated by Django 3.0.5 on 2020-04-21 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0074_merge_20200421_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityApprovalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100, verbose_name='Doc. No.')),
                ('document_pk', models.IntegerField(default=0)),
                ('notification', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('approval_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.WorkflowApprovalRule', verbose_name='Approval Level')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.DocumentTypeMaintenance', verbose_name='Doc.Type')),
                ('submit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.TransactiontypeMaintenance', verbose_name='Trans. Type')),
                ('utility_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.UtiliyAccountTypeMaintenance', verbose_name='Utility Account')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityApprovalItemCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CC')),
                ('utility_approval_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_dashboard.UtilityApprovalItem')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityApprovalItemApprover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('utility_approval_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_dashboard.UtilityApprovalItem')),
            ],
        ),
    ]
