# Generated by Django 3.0.3 on 2020-05-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmovement',
            name='stock_in',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemmovement',
            name='stock_out',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
    ]
