# Generated by Django 3.0.3 on 2020-05-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0082_auto_20200429_0207'),
        ('stock', '0002_auto_20200504_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentdetail',
            name='document_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustmentdetail',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.DocumentTypeMaintenance', verbose_name='Document Type'),
        ),
    ]
