# Generated by Django 3.0.3 on 2020-05-08 04:04

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20200327_1307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0082_auto_20200429_0207'),
        ('stock', '0005_itemmovement_submit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=1)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Document No')),
                ('document_pk', models.IntegerField(blank=True, null=True)),
                ('submit_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('attention', models.CharField(max_length=250)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.DepartmentMaintenance', verbose_name='Department')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.DocumentTypeMaintenance', verbose_name='Document Type')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.LocationMaintenance', verbose_name='Location')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.ProjectMaintenance', verbose_name='Project')),
                ('status', models.ForeignKey(blank=True, default=stock.models.stock_adjustment_default_status, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.StatusMaintenance', verbose_name='Status')),
                ('submit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.TransactiontypeMaintenance', verbose_name='Trans. Type')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.VendorMasterData', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Stock Return',
                'verbose_name_plural': 'Stock Return',
            },
        ),
        migrations.CreateModel(
            name='StockReturnDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Additional Description')),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, verbose_name='Qty')),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.Item', verbose_name='Item')),
                ('stock_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockReturn')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.UOMMaintenance', verbose_name='UOM')),
            ],
            options={
                'verbose_name': 'Stock Return Detail',
                'verbose_name_plural': 'Stock Return Detail',
            },
        ),
        migrations.CreateModel(
            name='StockReturnAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=stock.models.stock_return_directory_path, verbose_name='File Name')),
                ('attachment_date', models.DateField()),
                ('stock_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockReturn')),
            ],
            options={
                'verbose_name': 'Stock Return Attachment',
            },
        ),
    ]
