# Generated by Django 3.0.3 on 2020-02-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0004_itemgroupsmaintenance_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=1)),
                ('prefix', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=250)),
                ('origin', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=100)),
                ('hs_code', models.CharField(max_length=100)),
                ('minimum_quantity', models.IntegerField()),
                ('minimum_order_quantity', models.IntegerField()),
                ('standard_packing_quantity', models.IntegerField()),
                ('leadtime', models.IntegerField()),
                ('remarks', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
                ('item_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ItemClassesMaintenance', verbose_name='Item Class')),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ItemGroupsMaintenance', verbose_name='Item Group')),
            ],
        ),
    ]
