# Generated by Django 3.0.3 on 2020-02-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_itemgroupsmaintenance_parent_id'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
