# Generated by Django 3.0.3 on 2020-03-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20200225_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item Master Data', 'verbose_name_plural': 'Item Master Data'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='prefix',
        ),
    ]
