# Generated by Django 3.0.3 on 2020-03-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0040_auto_20200325_1643'),
        ('Inventory', '0004_auto_20200323_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.UOMMaintenance'),
        ),
    ]
