# Generated by Django 3.0.3 on 2020-03-27 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0045_auto_20200327_1130'),
        ('Inventory', '0005_item_item_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_uom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.UOMMaintenance'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemCategoryMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemcategorycreated_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemcategorymodified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='Inventory.ItemCategoryMaintenance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_subcategory', to='Inventory.ItemCategoryMaintenance'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_subsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_subsubcategory', to='Inventory.ItemCategoryMaintenance'),
        ),
    ]
