# Generated by Django 3.0.3 on 2020-03-27 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_auto_20200327_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_subcategory', to='Inventory.ItemCategoryMaintenance'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_subsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_subsubcategory', to='Inventory.ItemCategoryMaintenance'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(max_length=100),
        ),
    ]
