# Generated by Django 3.0.3 on 2020-03-28 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0041_countrymaintenance_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100)),
                ('document_pk', models.IntegerField(default=0)),
                ('notification', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('approval_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.WorkflowApprovalRule', verbose_name='Approval Level')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.DocumentTypeMaintenance', verbose_name='Document Type')),
                ('transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.TransactiontypeMaintenance', verbose_name='Transaction Type')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalItemCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalItem')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeMaintenance', verbose_name='CC')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalItemApprover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=0)),
                ('approval_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalItem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.UserMaintenance', verbose_name='User')),
            ],
        ),
    ]
