# Generated by Django 3.0.3 on 2020-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_auto_20200330_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalitem',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
