# Generated by Django 3.0.3 on 2020-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_approvalitem_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalitem',
            name='reason',
        ),
        migrations.AddField(
            model_name='approvalitemapprover',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='approvalitemapprover',
            name='status',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
