# Generated by Django 3.0.4 on 2020-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_auto_20200331_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalitemapprover',
            name='stage',
            field=models.IntegerField(default=1),
        ),
    ]
