# Generated by Django 3.0.4 on 2020-04-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0069_workflowapprovalrulegroupmaintenance_submitter_group'),
        ('approval', '0007_approvalitem_submit_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalitem',
            name='document_number',
            field=models.CharField(max_length=100, verbose_name='Doc. No.'),
        ),
        migrations.AlterField(
            model_name='approvalitem',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.DocumentTypeMaintenance', verbose_name='Doc.Type'),
        ),
        migrations.AlterField(
            model_name='approvalitem',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.TransactiontypeMaintenance', verbose_name='Trans. Type'),
        ),
    ]
