# Generated by Django 3.0.5 on 2020-04-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0009_approvalitem_approval_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalitem',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalitemapprover',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
