# Generated by Django 3.0.3 on 2020-04-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_overtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffot',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Document No'),
        ),
    ]
