# Generated by Django 3.0.3 on 2020-04-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_overtime', '0002_auto_20200413_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffotdetail',
            name='is_holiday',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
