# Generated by Django 3.0.3 on 2020-04-13 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_overtime', '0003_staffotdetail_is_holiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffotdetail',
            old_name='ot_time_ot',
            new_name='ot_time_out',
        ),
        migrations.AddField(
            model_name='staffot',
            name='submit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffotdetail',
            name='total_ot_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
