# Generated by Django 3.0.3 on 2020-04-13 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_overtime', '0004_auto_20200413_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffot',
            name='revision',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staffotdetail',
            name='staff_ot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_overtime.StaffOT', verbose_name='Staff OT'),
        ),
    ]
