# Generated by Django 3.0.3 on 2020-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_overtime', '0006_staffot_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffotdetail',
            name='ot_rate_per_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='staffotdetail',
            name='total_ot_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
