# Generated by Django 3.0.3 on 2020-04-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_overtime', '0008_auto_20200418_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffot',
            name='total_ot_hours',
            field=models.IntegerField(default=0),
        ),
    ]
