# Generated by Django 3.0.3 on 2020-03-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0014_auto_20200310_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('business_registration_no', models.CharField(max_length=30)),
                ('tax_id_1', models.CharField(max_length=100)),
                ('tax_id_2', models.CharField(max_length=100)),
                ('is_company', models.BooleanField()),
                ('created_by', models.CharField(editable=False, max_length=100)),
                ('created_timestamp', models.DateField(editable=False)),
                ('modified_by', models.CharField(editable=False, max_length=100)),
                ('modified_timestamp', models.DateField(editable=False)),
                ('currency', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.CurrencyMaintenance', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
