# Generated by Django 3.0.3 on 2020-03-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0014_auto_20200310_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('submit_date', models.DateField()),
                ('subject', models.CharField(max_length=250)),
                ('reference', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.DepartmentMaintenance', verbose_name='Department')),
                ('pay_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeMaintenance', verbose_name='Pay To')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ProjectMaintenance', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Advance Refund',
                'verbose_name_plural': 'Advance Refunds',
            },
        ),
    ]
