# Generated by Django 3.0.5 on 2020-04-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_auto_20200409_1247'),
        ('drawer_reimbursement', '0002_reimbursementrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalItem', verbose_name='Approval.'),
        ),
    ]
