# Generated by Django 3.0.5 on 2020-04-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawer_reimbursement', '0003_auto_20200420_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReimbursementRequest',
        ),
    ]
