# Generated by Django 3.0.5 on 2020-04-21 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0073_workflowapprovalrule_transaction_type'),
        ('drawer_reimbursement', '0005_reimbursementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementrequest',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.TransactiontypeMaintenance'),
        ),
    ]
