# Generated by Django 3.0.5 on 2020-04-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawer_reimbursement', '0006_auto_20200421_1027'),
        ('drawer_reimbursement', '0002_auto_20200420_2132'),
    ]

    operations = [
    ]
