# Generated by Django 3.0.5 on 2020-04-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawer_reimbursement', '0008_drawerreimbursement'),
        ('drawer_reimbursement', '0008_reimbursementrequest_transaction_type'),
    ]

    operations = [
    ]
