# Generated by Django 3.0.5 on 2020-04-27 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approval', '0010_auto_20200427_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.BooleanField(blank=True, default=False, null=True)),
                ('process_date', models.DateField(auto_now=True, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('completed_date', models.DateField(auto_now=True, null=True)),
                ('approval_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalItem')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_by_user', to=settings.AUTH_USER_MODEL)),
                ('process_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
