# Generated by Django 3.0.3 on 2020-02-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('business_registration_no', models.CharField(max_length=100)),
                ('tax_registration_no', models.CharField(max_length=100)),
                ('tax_registration_no_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=250)),
                ('phase_name', models.CharField(max_length=250)),
                ('sub_phase_name', models.CharField(max_length=250)),
                ('effect_start_date', models.DateField()),
                ('effect_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(max_length=100)),
                ('trans_type', models.CharField(max_length=100)),
                ('ceo_required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
