# Generated by Django 3.0.3 on 2020-02-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=250)),
                ('nick_name', models.CharField(max_length=250)),
                ('gender', models.BooleanField()),
                ('date_of_birth', models.DateField()),
                ('tax_registration_no_2', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTermMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('days', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=250)),
                ('user_group', models.CharField(max_length=250)),
                ('signature', models.FileField(upload_to='')),
            ],
        ),
    ]
