# Generated by Django 3.0.3 on 2020-02-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_employeemaintenance_paymenttermmaintenance_usermaintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemClassesMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_class_code', models.CharField(max_length=100)),
                ('item_class_name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroupsMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group_code', models.CharField(max_length=100)),
                ('item_group_name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_code', models.CharField(max_length=100)),
                ('loc_name', models.CharField(max_length=250)),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
            ],
        ),
    ]
