# Generated by Django 3.0.3 on 2020-02-25 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20200225_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaintenance',
            name='currency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.CurrencyMaintenance', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='itemgroupsmaintenance',
            name='parent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.ItemGroupsMaintenance', verbose_name='Parent Group'),
        ),
        migrations.AlterField(
            model_name='projectmaintenance',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='statusmaintenance',
            name='document_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.DocumentTypeMaintenance', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='usermaintenance',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='document_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.DocumentTypeMaintenance', verbose_name='Document Type'),
        ),
    ]
