# Generated by Django 3.0.3 on 2020-02-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20200225_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmaintenance',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.DocumentTypeMaintenance', verbose_name='Document Type'),
        ),
    ]
