# Generated by Django 3.0.3 on 2020-02-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20200225_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmaintenance',
            name='document_type',
        ),
    ]
