# Generated by Django 3.0.3 on 2020-02-25 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_remove_statusmaintenance_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmaintenance',
            name='document_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.DocumentTypeMaintenance', verbose_name='Document Type'),
        ),
    ]
