# Generated by Django 3.0.3 on 2020-03-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_workflowapprovalrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaintenance',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=25),
        ),
    ]
