# Generated by Django 3.0.3 on 2020-03-07 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20200307_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CountryMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=250)),
                ('alpha_2', models.CharField(max_length=2)),
                ('alpha_3', models.CharField(max_length=3)),
                ('iso3166_2', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGroupMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=250)),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePositionMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=250)),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=100)),
                ('region_name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemFlagMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(max_length=250)),
                ('table_id', models.IntegerField()),
                ('created_by', models.CharField(editable=False, max_length=100)),
                ('created_timestamp', models.DateField(editable=False)),
                ('modified_by', models.CharField(editable=False, max_length=100)),
                ('modified_timestamp', models.DateField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='VendorGroupMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=15)),
                ('group_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(editable=False, max_length=100)),
                ('created_timestamp', models.DateField(editable=False)),
                ('modified_by', models.CharField(editable=False, max_length=100)),
                ('modified_timestamp', models.DateField(editable=False)),
            ],
        ),
        migrations.RenameField(
            model_name='companymaintenance',
            old_name='tax_registration_no',
            new_name='tax_id_1',
        ),
        migrations.RenameField(
            model_name='companymaintenance',
            old_name='tax_registration_no_2',
            new_name='tax_id_2',
        ),
        migrations.RemoveField(
            model_name='employeemaintenance',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employeemaintenance',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeemaintenance',
            name='employee_code',
        ),
        migrations.RemoveField(
            model_name='employeemaintenance',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employeemaintenance',
            name='tax_registration_no_2',
        ),
        migrations.AddField(
            model_name='currencymaintenance',
            name='alphabet',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencymaintenance',
            name='created_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencymaintenance',
            name='created_timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencymaintenance',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencymaintenance',
            name='modified_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencymaintenance',
            name='modified_timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemaintenance',
            name='created_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemaintenance',
            name='created_timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemaintenance',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemaintenance',
            name='modified_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemaintenance',
            name='modified_timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemaintenance',
            name='reporting_officer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeMaintenance', verbose_name='Reporting Officer'),
        ),
        migrations.AlterField(
            model_name='companymaintenance',
            name='business_registration_no',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='EmployeeProjectMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
                ('employee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeMaintenance', verbose_name='Employee')),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.ProjectMaintenance', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDepartmentMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.DepartmentMaintenance', verbose_name='Department')),
                ('employee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeMaintenance', verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBranchMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('created_timestamp', models.DateField()),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_timestamp', models.DateField()),
                ('branch', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.BranchMaintenance', verbose_name='Branch')),
                ('employee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeMaintenance', verbose_name='Employee')),
            ],
        ),
        migrations.AddField(
            model_name='companymaintenance',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.RegionMaintenance', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='currencymaintenance',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.CountryMaintenance', verbose_name='Coountry'),
        ),
        migrations.AddField(
            model_name='employeemaintenance',
            name='position_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeePositionMaintenance', verbose_name='Position'),
        ),
    ]
