# Generated by Django 3.0.3 on 2020-03-10 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20200307_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymaintenance',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.CountryMaintenance', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='employeemaintenance',
            name='created_by',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeemaintenance',
            name='created_timestamp',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='employeemaintenance',
            name='modified_by',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeemaintenance',
            name='modified_timestamp',
            field=models.DateField(editable=False),
        ),
    ]
