# Generated by Django 3.0.3 on 2020-03-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_auto_20200310_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymaintenance',
            name='company_code',
        ),
    ]
