# Generated by Django 3.0.3 on 2020-03-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_auto_20200310_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchmaintenance',
            name='branch_code',
        ),
        migrations.RemoveField(
            model_name='companymaintenance',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='countrymaintenance',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='currencymaintenance',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='departmentmaintenance',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='documenttypemaintenance',
            name='document_type_code',
        ),
        migrations.RemoveField(
            model_name='employeegroupmaintenance',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='itemclassesmaintenance',
            name='item_class_code',
        ),
        migrations.RemoveField(
            model_name='itemgroupsmaintenance',
            name='item_group_code',
        ),
        migrations.RemoveField(
            model_name='locationmaintenance',
            name='loc_code',
        ),
        migrations.RemoveField(
            model_name='regionmaintenance',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='vendorgroupmaintenance',
            name='group_code',
        ),
        migrations.CreateModel(
            name='VendorMasterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('business_registration_no', models.CharField(max_length=30)),
                ('tax_id_1', models.CharField(max_length=100)),
                ('tax_id_2', models.CharField(max_length=100)),
                ('is_company', models.BooleanField()),
                ('created_by', models.CharField(editable=False, max_length=100)),
                ('created_timestamp', models.DateField(editable=False)),
                ('modified_by', models.CharField(editable=False, max_length=100)),
                ('modified_timestamp', models.DateField(editable=False)),
                ('currency', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.CurrencyMaintenance', verbose_name='Currency')),
                ('vendor_group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.VendorGroupMaintenance', verbose_name='Vendor Group')),
            ],
        ),
    ]
