# Generated by Django 3.0.3 on 2020-03-10 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_remove_companymaintenance_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaintenance',
            name='created_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymaintenance',
            name='created_timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymaintenance',
            name='modified_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymaintenance',
            name='modified_timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
