# Generated by Django 3.0.3 on 2020-03-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20200310_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_cde', models.CharField(max_length=100)),
                ('tax_name', models.CharField(max_length=250)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(editable=False, max_length=100)),
                ('created_timestamp', models.DateField(editable=False)),
                ('modified_by', models.CharField(editable=False, max_length=100)),
                ('modified_timestamp', models.DateField(editable=False)),
            ],
        ),
    ]
