# Generated by Django 3.0.3 on 2020-03-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_auto_20200310_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaintenance',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxmaintenance',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taxmaintenance',
            name='created_timestamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taxmaintenance',
            name='modified_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taxmaintenance',
            name='modified_timestamp',
            field=models.DateField(),
        ),
    ]
