# Generated by Django 3.0.3 on 2020-03-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_employeemaintenance_is_active'),
        ('administration', '0014_auto_20200310_1519'),
    ]

    operations = [
    ]
