# Generated by Django 3.0.3 on 2020-03-11 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_auto_20200311_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowapprovalrule',
            name='document_amount_range',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Document Amount Range From (RM)'),
        ),
        migrations.AlterField(
            model_name='workflowapprovalrule',
            name='document_amount_range2',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='workflowapprovalrule',
            name='no_of_groupa',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='No of Group A User'),
        ),
        migrations.AlterField(
            model_name='workflowapprovalrule',
            name='no_of_groupb',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='No of Group B User'),
        ),
    ]
