# Generated by Django 3.0.3 on 2020-03-11 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_auto_20200311_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowapprovalrule',
            name='no_of_groupa',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='No of Group A User'),
        ),
        migrations.AlterField(
            model_name='workflowapprovalrule',
            name='no_of_groupb',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='No of Group B User'),
        ),
    ]
