# Generated by Django 3.0.3 on 2020-03-11 10:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_workflowapprovalrule_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowApprovalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_group_name', models.CharField(max_length=250)),
                ('no_of_group', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='No of User')),
                ('is_active', models.BooleanField()),
                ('user_group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeGroupMaintenance', verbose_name='User Group')),
            ],
        ),
        migrations.RenameField(
            model_name='workflowapprovalrule',
            old_name='description',
            new_name='approval_rule_name',
        ),
        migrations.RemoveField(
            model_name='workflowapprovalrule',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='workflowapprovalrule',
            name='no_of_groupa',
        ),
        migrations.RemoveField(
            model_name='workflowapprovalrule',
            name='no_of_groupb',
        ),
        migrations.CreateModel(
            name='WorkflowApprovalRuleGroupMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_condition', models.CharField(choices=[('And', 'And'), ('Or', 'Or')], max_length=15, null=True)),
                ('approval_group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.WorkflowApprovalGroup', verbose_name='Approval Group')),
                ('approval_rule', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.WorkflowApprovalRule', verbose_name='Approval Level')),
            ],
        ),
    ]
