# Generated by Django 3.0.3 on 2020-03-11 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0025_auto_20200311_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowapprovalgroup',
            name='no_of_group',
        ),
        migrations.AddField(
            model_name='workflowapprovalgroup',
            name='no_of_person',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='No of person'),
            preserve_default=False,
        ),
    ]
