# Generated by Django 3.0.3 on 2020-03-22 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0027_auto_20200320_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroupsmaintenance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemgroupsmaintenance',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
