# Generated by Django 3.0.3 on 2020-03-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0029_auto_20200322_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroupsmaintenance',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemgroupsmaintenance',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
