# Generated by Django 3.0.3 on 2020-03-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0030_auto_20200322_1215'),
        ('administration', '0027_drawermaintenance'),
    ]

    operations = [
    ]
