# Generated by Django 3.0.3 on 2020-03-22 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0032_auto_20200322_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaintenance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companycreated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companymaintenance',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companymaintenance',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companymodified_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companymaintenance',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
