# Generated by Django 3.0.3 on 2020-03-23 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0034_auto_20200322_1840'),
        ('administration', '0031_merge_20200323_0206'),
    ]

    operations = [
    ]
