# Generated by Django 3.0.3 on 2020-03-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0038_memotemplatemaintenance_paymentmodemaintenance_transactiontypemaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaintenance',
            name='employee_signature',
            field=models.FileField(default=1, upload_to='', verbose_name='Employee Signature'),
            preserve_default=False,
        ),
    ]
