# Generated by Django 3.0.3 on 2020-03-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0040_auto_20200325_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymaintenance',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.CurrencyMaintenance', verbose_name='Currency'),
            preserve_default=False,
        ),
    ]
