# Generated by Django 3.0.3 on 2020-03-27 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0041_countrymaintenance_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaintenance',
            name='employee_department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeDepartmentMaintenance', verbose_name='Department'),
        ),
    ]
