# Generated by Django 3.0.3 on 2020-03-27 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0044_auto_20200327_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebranchmaintenance',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.BranchMaintenance', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='employeedepartmentmaintenance',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.DepartmentMaintenance', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employeeprojectmaintenance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ProjectMaintenance', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='workflowapprovalrulegroupmaintenance',
            name='approval_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.WorkflowApprovalGroup', verbose_name='Approval Group'),
        ),
        migrations.AlterField(
            model_name='workflowapprovalrulegroupmaintenance',
            name='next_condition',
            field=models.CharField(blank=True, choices=[('And', 'And'), ('Or', 'Or')], max_length=15, null=True),
        ),
    ]
