# Generated by Django 3.0.3 on 2020-03-27 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0045_auto_20200327_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
                ('capital', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CountryMaintenance', verbose_name='Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statecreated_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statemodified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vendormaindata',
            name='is_qualified',
            field=models.BooleanField(default=False, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencymaintenance',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CountryMaintenance', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='vendormaindata',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CurrencyMaintenance', verbose_name='Currency'),
        ),
        migrations.CreateModel(
            name='VendorContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss', 'Miss')], max_length=20)),
                ('contact_person', models.CharField(max_length=100)),
                ('tel_no1', models.CharField(max_length=20, verbose_name='Tel 1')),
                ('tel_no2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel 2')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ic_or_passport_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='IC/Passport No.')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='D.O.B')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='Position')),
                ('vendor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.VendorMainData')),
            ],
        ),
        migrations.CreateModel(
            name='VendorAddressDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(max_length=150)),
                ('address3', models.CharField(blank=True, max_length=150, null=True)),
                ('address4', models.CharField(blank=True, max_length=150, null=True)),
                ('address_zip', models.IntegerField(verbose_name='Zip')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CountryMaintenance', verbose_name='Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.StateMaintenance', verbose_name='State')),
                ('vendor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.VendorMainData')),
            ],
        ),
    ]
