# Generated by Django 3.0.3 on 2020-03-27 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0047_auto_20200327_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontactdetail',
            name='contact_person',
            field=models.CharField(max_length=100, verbose_name='Contact Person Name'),
        ),
        migrations.AlterField(
            model_name='vendormasterdata',
            name='is_qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendormasterdata',
            name='vendor_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.VendorGroupMaintenance', verbose_name='Vendor Group'),
        ),
        migrations.CreateModel(
            name='VendorCategoryMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_category_name', models.CharField(max_length=200, verbose_name='Vendor Category Name')),
                ('is_active', models.BooleanField()),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendorcategorycreated_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendorcategorymodified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vendormasterdata',
            name='vendor_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.VendorCategoryMaintenance', verbose_name='Vendor Category'),
            preserve_default=False,
        ),
    ]
