# Generated by Django 3.0.3 on 2020-03-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0048_auto_20200327_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss', 'Miss')], max_length=20)),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contact Person Name')),
                ('tel_no1', models.CharField(max_length=20, verbose_name='Tel 1')),
                ('tel_no2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel 2')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ic_or_passport_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='IC/Passport No.')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='D.O.B')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='Position')),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddressDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(max_length=150)),
                ('address3', models.CharField(blank=True, max_length=150, null=True)),
                ('address4', models.CharField(blank=True, max_length=150, null=True)),
                ('address_zip', models.IntegerField(verbose_name='Zip')),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.CompanyMaintenance')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CountryMaintenance', verbose_name='Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.StateMaintenance', verbose_name='State')),
            ],
        ),
    ]
