# Generated by Django 3.0.3 on 2020-03-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0049_companyaddressdetail_companycontactdetail'),
        ('administration', '0042_auto_20200328_0906'),
    ]

    operations = [
    ]
