# Generated by Django 3.0.3 on 2020-03-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0050_staffhiretypemaintenance_staffpositiontitlemaintenance_utiliyaccounttypemaintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencymaintenance',
            name='country',
        ),
    ]
