# Generated by Django 3.0.3 on 2020-03-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0042_auto_20200328_0906'),
        ('administration', '0051_remove_currencymaintenance_country'),
    ]

    operations = [
    ]
