# Generated by Django 3.0.3 on 2020-03-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0051_auto_20200329_2121'),
        ('administration', '0053_auto_20200329_1237'),
    ]

    operations = [
    ]
