# Generated by Django 3.0.3 on 2020-03-30 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0054_merge_20200330_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaintenance',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CurrencyMaintenance', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='companymaintenance',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.RegionMaintenance', verbose_name='Region'),
        ),
    ]
