# Generated by Django 3.0.3 on 2020-03-30 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0055_auto_20200330_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaintenance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.BranchMaintenance', verbose_name='Branch'),
        ),
    ]
