# Generated by Django 3.0.3 on 2020-03-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0056_companymaintenance_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaintenance',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.BranchMaintenance', verbose_name='Branch'),
            preserve_default=False,
        ),
    ]
