# Generated by Django 3.0.3 on 2020-03-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0054_merge_20200330_1010'),
        ('administration', '0057_auto_20200330_1428'),
    ]

    operations = [
    ]
