# Generated by Django 3.0.3 on 2020-03-31 06:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0009_auto_20200328_1644'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0059_auto_20200331_0248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffHireTypeMaintenance',
            new_name='StaffemploymentTypeMaintenance',
        ),
        migrations.RenameField(
            model_name='staffemploymenttypemaintenance',
            old_name='hire_type_name',
            new_name='employment_type_name',
        ),
    ]
