# Generated by Django 3.0.4 on 2020-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0062_drawerusermaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowapprovalrulegroupmaintenance',
            name='next_condition',
            field=models.CharField(blank=True, choices=[('And', 'And'), ('Or', 'Or')], max_length=15, null=True),
        ),
    ]
