# Generated by Django 3.0.4 on 2020-04-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0063_auto_20200403_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowapprovalrule',
            name='ceo_approve',
            field=models.BooleanField(default=False, verbose_name='CEO Approval'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflowapprovalrule',
            name='supervisor_approve',
            field=models.BooleanField(verbose_name='Reporting Officer Approval'),
        ),
    ]
