# Generated by Django 3.0.4 on 2020-04-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0064_auto_20200404_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymaintenance',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.CurrencyMaintenance', verbose_name='Currency'),
        ),
    ]
