# Generated by Django 3.0.4 on 2020-04-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0066_auto_20200405_1311'),
        ('administration', '0066_workflowapprovalrule_ceo_approve_overwrite'),
    ]

    operations = [
    ]
