# Generated by Django 3.0.4 on 2020-04-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0068_holidayeventmaintenance_otratemaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowapprovalrulegroupmaintenance',
            name='submitter_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitter_group', to='administration.EmployeeGroupMaintenance', verbose_name='Submitter Group'),
        ),
    ]
