# Generated by Django 3.0.3 on 2020-04-15 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0069_workflowapprovalrulegroupmaintenance_submitter_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayeventmaintenance',
            name='ot_rate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.OTRateMaintenance', verbose_name='OT Rate'),
            preserve_default=False,
        ),
    ]
