# Generated by Django 3.0.3 on 2020-04-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0070_holidayeventmaintenance_ot_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otratemaintenance',
            name='ot_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='OT Rate'),
        ),
    ]
