# Generated by Django 3.0.5 on 2020-04-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0071_auto_20200415_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypemaintenance',
            name='is_utility',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowapprovalrule',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.TransactiontypeMaintenance'),
        ),
    ]
