# Generated by Django 3.0.3 on 2020-04-20 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0072_transactiontypemaintenance_is_utility'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowapprovalrule',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.TransactiontypeMaintenance'),
        ),
    ]
