# Generated by Django 3.0.5 on 2020-04-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0072_auto_20200420_2112'),
        ('administration', '0073_workflowapprovalrule_transaction_type'),
    ]

    operations = [
    ]
