# Generated by Django 3.0.5 on 2020-04-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0074_merge_20200421_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='utiliyaccounttypemaintenance',
            name='account_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
