# Generated by Django 3.0.5 on 2020-04-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0075_utiliyaccounttypemaintenance_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utiliyaccounttypemaintenance',
            name='account_no',
            field=models.CharField(max_length=100),
        ),
    ]
