# Generated by Django 3.0.5 on 2020-04-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0074_merge_20200421_1318'),
        ('administration', '0078_hrplatformmaintenance'),
    ]

    operations = [
    ]
