# Generated by Django 3.0.5 on 2020-04-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0079_merge_20200426_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttypemaintenance',
            name='send_to_account',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
