# Generated by Django 3.0.5 on 2020-04-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0080_documenttypemaintenance_send_to_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttypemaintenance',
            name='send_to_account',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
