# Generated by Django 3.0.5 on 2020-04-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0081_auto_20200429_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttypemaintenance',
            name='send_to_account',
        ),
        migrations.AddField(
            model_name='transactiontypemaintenance',
            name='send_to_account',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
