# Generated by Django 3.0.5 on 2020-05-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0082_auto_20200429_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmaintenance',
            name='can_access_accounts_dashboard',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
