# Generated by Django 3.0.5 on 2020-05-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0083_departmentmaintenance_can_access_accounts_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentmaintenance',
            old_name='can_access_accounts_dashboard',
            new_name='access_accounts_dashboard',
        ),
    ]
